
version: '3'

services:
  backend:
    build: backend/
    restart: unless-stopped
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - filestore
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/swkom
      SPRING_DATASOURCE_USERNAME: paperless
      SPRING_DATASOURCE_PASSWORD: pwd123456
      MINIO_URL: http://filestore:9000
      SPRING_RABBITMQ_HOST: rabbitmq
  
  frontend:
    build: frontend/src-ui/
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - 8001:80

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: pwd123456
      POSTGRES_DB: swkom
    ports:
      - "5432:5432"

  filestore:
    image: quay.io/minio/minio
    # volumes: 
    #   - miniostorage:/data
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: PAPERLESS
      MINIO_ROOT_PASSWORD: PASSWORD
    ports:
      - 9000:9000          # just for development
      - 9090:9090          # for browser access to the management ui
    command: server /data --console-address ":9090"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672     # just for development
      - 15672:15672   # for browser access to the management ui
    environment:
      RABBITMQ_DEFAULT_USER: PAPERLESS
      RABBITMQ_DEFAULT_PASS: PASSWORD

#  ocrworker:
#    build: ocrworker/
#    restart: unless-stopped
#    depends_on:
#      - filestore
#    ports:
#      - 8090:8090

# volumes:
  # miniostorage:
  # TODO: add volumes for postgres, rabbitmq