
version: '3'

services:
  backend:
    build: backend/
    restart: unless-stopped
    ports:
      - 8000:8000
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/swkom
      SPRING_DATASOURCE_USERNAME: paperless
      SPRING_DATASOURCE_PASSWORD: pwd123456
  
  frontend:
    build: frontend/src-ui/
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - 8001:80

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: pwd123456
      POSTGRES_DB: swkom
    ports:
      - "5432:5432"
