# Use the official Elasticsearch image from Docker Hub
FROM docker.elastic.co/elasticsearch/elasticsearch:7.15.1

# Add custom configurations if needed
# COPY elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml

# Expose ports
EXPOSE 9200 9300
